### PR TITLE
Correct wrong parameter name in Pgetpriority and Psetpriority system …

### PR DESCRIPTION
**Pull request by DavidGZ**
…calls

### CODE REVIEW

**Comment by th-otto** [comment]
Looks like a duplicate of the other commit?

**Comment by DavidGZ** [comment]
No, it shouldn't be but the other commit and other stuff slipped in this pull-request. Let me remake it.
I don't get used to the pull-request system, it makes me loose more time that the old patch system.

**Comment by DavidGZ** [comment]
I think now is OK. Thanks for merging!

**Comment by th-otto** [comment]
Yes, that happens when the master branch of your fork was not up-to-date. But the actual commit with the typo has been merged already by the other PR.

**Comment by DavidGZ** [comment]
Thorsten, the commit that was originally in this pull-request is not merged yet.

**Comment by th-otto** [comment]
Hm. I can neither reopen nor merge the commit. Is the commit still in your repo? I see that you force-pushed something. Maybe creating a new branch, and just cherry-picking that commit works.

**Comment by th-otto** [comment]
Ah lol you already did that.

**Pull request closed without merging**
