### PR TITLE
Correct return type for Tgetdate() to uint16_t

### PR DESCRIPTION
**Pull request by rosenrost**

### CODE REVIEW

**Comment by th-otto** [comment]
Please be careful to not mess up the german umlauts (seems they are converted to utf-8 in your patch)

**Comment by mikrosk** [comment]
Indeed, always set your editor's and/or git client's encoding to CP437 or similar (but definitely not UTF-8).

**Comment by rosenrost** [comment]
Sorry for that, I changed the file using the online editor and wasn't aware that it seems to automatically convert the characters to UTF8.

**Comment by rosenrost** [comment]
The latest commit uses the correct character set.

**Comment by th-otto** [comment]
> Sorry for that, I changed the file using the online editor and wasn't aware that it seems to automatically convert the characters to UTF8.

Unfortunately that does not work, because the online editor does not know anything about 8bit character set encodings.

In the long term, would be best to avoid such non-ascii characters and replace them by udos syntax. I've already done that in some places, but there are lots to do, and it cannot be done automatically, because those commands are not interpreted in `verbatim` environments.

**Pull request merged**
