### PR TITLE
Resolves #112 : note on VgetRGB/VsetRGB 

### LINKED ISSUE #112: VgetRGB()/VsetRGB() should be called with the correct number of colors
References : a sequence of posts on atari forum [post 1 (sequence of calls does not work as expected)](https://www.atari-forum.com/viewtopic.php?p=438714#p438714) ; [post 2 (hypothesis)](https://www.atari-forum.com/viewtopic.php?p=438715#p438715) and [post 3(confirm that hypothesis is correct)](https://www.atari-forum.com/viewtopic.php?p=438717#p438717)

One should not try to save/restore more colors than supported by the video mode.

>Edit 
>location on the doc : https://freemint.github.io/tos.hyp/en/Screen_functions.html#VgetRGB

### PR DESCRIPTION
**Pull request by sporniket**

### CODE REVIEW

**Comment by mikrosk** [comment]
I think a better (more detailed) description would be helpful here. Although I am aware of this behaviour, I've been lazy to verify my hypothesis: is it because VgetRgb(256) reads 16 initialised colours + 240 random colours and then does the same with VsetRgb(256) but due to bank mirroring only the last 16 (garbage) colours are applied?

**Comment by sporniket** [comment]
I have created this PR to not let the info be lost after the poster on atari-forum did report this find. I have no Falcon to detail the actual behavior. 

I believe the warning is helpfull to people not being aware of that, even if it does not details what actually happen. It can always be polished later.

**Comment by sporniket** [comment]
@mikrosk if you can check and details the actual behaviour, I will happily update this PR :)

**Comment by th-otto** [comment]
I would have thought that it is rather obvious that you should not try using invalid color indices. Of course that does not mean that a clarification is not helpful. But i guess that also applies to lot of other places.

**Comment by th-otto** [comment]
BTW, there is a typo in your 2nd patch (b! instead of !b). See also error messages in https://github.com/freemint/tos.hyp/actions/runs/3194724405/jobs/5218767278

**Comment by sporniket** [comment]
@th-otto should be good now

**Pull request merged**
