### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by th-otto**

### CODE REVIEW

**Comment by th-otto** [comment]
First off: who are you? ;) I dont like comments from people posting only with a pseudonym.

Regarding your request: yes i know, colour vs. color is arguable. My feeling about this is that all VDI function names (vsl_color, vst_color etc.) use the term color, so it would be more consistent to use that term in the descriptions, too. And the html pages are marked as en_US, not en_UK.

**Comment by atic-atac** [comment]
Err, so I'm the admin.

Don't list color vs colour as a typo then, it's not. Please extract these changes into another change that says something akin to what it's doing.

**Comment by mikrosk** [comment]
@atic-atac I'm already in touch with Thorsten aka @th-otto 

First the PRs must be rebased on master (every one of them) else you'd get yes, 926 changed files (and commits from previous PRs).

Then the next step can be made (grouping similar PRs etc).

**Comment by th-otto** [comment]
> Err, so I'm the admin.

Ah hi Alan then ;) Apologies, but how are ppl supposed to know?

> Don't list color vs colour as a typo then, it's not.

If that is the case, then you are right and it should be part of the other patch. Maybe i just missed it. But before i spend a lot of time changing that again (and maybe all following patches), i would just ask to decide first wether to accept that colour->color patches.

>This is an awful lot of "fix typos" requests to review.
>Can you collapse all of the "fix typos" into one commit.

The reason is simple that i gathered them over quite some time. If you detect a typo in source, fix & commit it, then half a year later detect another one, are you going to revert the first patch only to merge it with the 2nd? I guess not. So i would prefer it to leave it as is, everything else would just be a lot work for me only to save someone a few clicks.

> "small changes" doesn't exactly spell out what the change is doing.

Hm yes, i just  could not find a better name, its only 1 changed line after all :)

**Comment by mikrosk** [comment]
@th-otto more than one patch is no problem -- PR shows you all changed files at once. So if you have two patches which are just typo fixes, you can of course put them into one PR branch. I guess Alan's point is to separate things so one can review them.

**Pull request closed without merging**
